# Generated by Django 4.0.3 on 2022-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondname',
            field=models.CharField(max_length=50, null=True, verbose_name='SecondName'),
        ),
    ]
