# Generated by Django 4.0.3 on 2022-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_secondname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secondname',
        ),
    ]
