# Generated by Django 4.0.3 on 2022-05-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_category_photo'),
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.category', verbose_name='Category'),
        ),
    ]
